Repository human-osaka-game-2018/Summoners-Aster, pull requests merged in 2019-03, with the labels that each got.

#9 Issueのテンプレートを追加
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
Labels: enhancement

#11 Pull Requestのテンプレートを追加
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#15 シーン基底クラスの作成
  Summoners'Aster/SceneSwitcher/Scene/Scene.cpp
  Summoners'Aster/SceneSwitcher/Scene/Scene.h
  Summoners'Aster/Summoners'Aster.vcxproj
  Summoners'Aster/Summoners'Aster.vcxproj.filters
Labels: enhancement

#28 パスの修正
  Summoners-Aster/Summoners-Aster.vcxproj
  Summoners-Aster/Summoners-Aster.vcxproj.filters
Labels: bug

#29 ✨ 動作が完了しているかを保持するオブジェクトクラスを継承したクラスの作成
  Summoners-Aster/ObjectIntegrator/Object/Object.cpp
  Summoners-Aster/ObjectIntegrator/Object/Object.h
  Summoners-Aster/ObjectIntegrator/Object/Task.cpp
  Summoners-Aster/ObjectIntegrator/Object/Task.h
  Summoners-Aster/Summoners-Aster.vcxproj.filters
Labels: enhancement

#30 ✨ オブジェクトクラスを順番に動かしたりできるクラスの追加
  Summoners-Aster/ObjectIntegrator/TaskScheduler.cpp
  Summoners-Aster/ObjectIntegrator/TaskScheduler.h
  Summoners-Aster/Summoners-Aster.vcxproj
  Summoners-Aster/Summoners-Aster.vcxproj.filters
Labels: enhancement

#39 ♻️ タスクスケジューラのリファクタリング
  Summoners-Aster/ObjectIntegrator/TaskScheduler.cpp
  Summoners-Aster/ObjectIntegrator/TaskScheduler.h
Labels: correction
